# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 🏗 Build
on:
  workflow_dispatch:
    inputs:
      MOZ_BUILD_DATE:
        description: Build date override
        required: false
        type: string
      PRE_RELEASE:
        description: Mark build as pre-release
        required: false
        type: string
      TAG_VERSION:
        description: Optional display version override
        required: false
        type: string
      TRIGGER_EVENT:
        description: Trigger event for the workflow
        required: false
        default: workflow_dispatch
        type: string
  workflow_call:
    inputs:
      MOZ_BUILD_DATE:
        required: false
        type: string
      PRE_RELEASE:
        required: false
        type: string
      TRIGGER_EVENT:
        description: Trigger event for the workflow
        required: false
        type: string
      TAG_VERSION:
        required: false
        type: string
    outputs:
      versiondisplay:
        description: Output display version
        value: '${{ jobs.build-windows-x64-stage-1.outputs.versionout }}'
      run_id:
        description: Build workflow run id
        value: '${{ jobs.build-windows-x64-stage-1.outputs.run_id }}'
    secrets:
      MOZ_API_KEY:
        required: true
env:
  CARGO_TERM_COLOR: always
  MOZ_BUILD_DATE: '${{ inputs.MOZ_BUILD_DATE }}'
  PRE_RELEASE: '${{ inputs.PRE_RELEASE }}'
  SCCACHE_GHA_ENABLED: 'true'
jobs:
  build-windows-x64-stage-1:
    name: 🪟 Windows Stage 1
    runs-on:
      - warp-ubuntu-latest-x64-16x
    concurrency:
      group: '${{ github.head_ref }}-windows-x64-stage-1'
      cancel-in-progress: true
    env:
      MOZCONFIG: .mozconfig-x86_64-pc-windows-msvc
      WINEDEBUG: '-all'
      ARCH: x86_64-pc-mingw32
    outputs:
      versionout: '${{ steps.versionexport.outputs.version }}'
      run_id: '${{ steps.runid.outputs.run_id }}'
    steps:
      - name: ⚡ Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 💿 Build dependencies
        run: |
          sudo apt update
          sudo apt install msitools
          rustup override set 1.90.0
          rustup target add x86_64-pc-windows-msvc
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L "https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
          curl https://rclone.org/install.sh | sudo bash
      - name: 📤 Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: 📣 Override version_display.txt
        run: |
          if [[ -n ${{ inputs.TAG_VERSION }} ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: 📣 Export VERSION_DISPLAY
        id: versionexport
        run: echo "version=$(echo ${{ env.VERSION_DISPLAY }})" >> $GITHUB_OUTPUT
      - name: 📣 Export run id
        id: runid
        run: echo "run_id=${GITHUB_RUN_ID}" >> "$GITHUB_OUTPUT"
      - name: 🏗 Build
        run: |
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          fi
          if [[ $PRE_RELEASE != 'true' ]]; then
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export GEN_PGO=1
          ./mach build
      - name: 📦 Package
        run: |
          ./mach package
      - name: 📣 Save build metadata
        run: |
          mkdir -p artifacts
          {
            echo "VERSION_DISPLAY=${VERSION_DISPLAY}"
            echo "PRE_RELEASE=${PRE_RELEASE}"
            echo "MOZ_BUILD_DATE=${MOZ_BUILD_DATE}"
            echo "TAG_VERSION=${{ inputs.TAG_VERSION }}"
            echo "BUILD_RUN_ID=${GITHUB_RUN_ID}"
            echo "COMMIT_SHA=${GITHUB_SHA}"
          } > artifacts/build-metadata.env
        shell: bash
      - name: ↑ Upload metadata
        uses: actions/upload-artifact@v6
        with:
          name: build-metadata
          path: artifacts/build-metadata.env
      - name: ↑ Upload Stage 1 Artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-${{ env.ARCH }}-stage-1
          path: |
            obj-${{ env.ARCH }}/dist/waterfox
  build-windows-x64-stage-2:
    name: 🪟 Windows Stage 2
    defaults:
      run:
        shell: bash
    needs:
      - build-windows-x64-stage-1
    runs-on: windows-2025
    concurrency:
      group: '${{ github.head_ref }}-windows-x64-stage-2'
      cancel-in-progress: true
    env:
      ARCH: x86_64-pc-mingw32
    steps:
      - name: ⚙️ Setup
        run: |
          curl -L https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe --output MozillaBuildSetup-Latest.exe
          7z x MozillaBuildSetup-Latest.exe -o/c/mozilla-build
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.win64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          7z x "clang.tar.zst" -so | 7z x -aoa -si -ttar -o$HOME/.mozbuild
      - name: 📤 Checkout
        uses: actions/checkout@v6
      - name: ↓ Download Stage 1 Windows artifact
        uses: actions/download-artifact@v7
        with:
          name: windows-${{ env.ARCH }}-stage-1
          path: obj-${{ env.ARCH }}/dist/waterfox
      - name: 🏗 Run PGO
        shell: pwsh
        run: |
          ls obj-${{ env.ARCH }}/dist/
          ls obj-${{ env.ARCH }}/dist/waterfox
          rm .mozconfig
          python mach configure --disable-bootstrap
          $env:LLVM_PROFDATA = $HOME + '/.mozbuild/clang/bin/llvm-profdata.exe'; $env:JARLOG_FILE = 'en-US.log'; python mach python build/pgo/profileserver.py --binary ./obj-${{ env.ARCH }}/dist/waterfox/waterfox.exe
      - name: ↑ Upload Stage 2 Artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-${{ env.ARCH }}-stage-2
          path: |
            merged.profdata
            en-US.log
  build-windows-x64-stage-3:
    name: 🪟 Windows Stage 3
    needs:
      - build-windows-x64-stage-2
    runs-on:
      - warp-ubuntu-latest-x64-32x
    concurrency:
      group: '${{ github.head_ref }}-windows-x64-stage-3'
      cancel-in-progress: true
    env:
      MOZCONFIG: .mozconfig-x86_64-pc-windows-msvc
      WINEDEBUG: '-all'
      ARCH: x86_64-pc-mingw32
    steps:
      - name: ⚡ Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 💿 Build dependencies
        run: |
          sudo apt update
          sudo apt install msitools
          rustup override set 1.90.0
          rustup target add x86_64-pc-windows-msvc
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L https://github.com/ebourg/jsign/releases/download/7.4/jsign_7.4_all.deb --output jsign_7.4_all.deb
          sudo apt install -y ./jsign_7.4_all.deb
          curl -L "https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
          curl https://rclone.org/install.sh | sudo bash
      - name: 📤 Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: 📣 Override version_display.txt
        run: |
          if [[ -n ${{ inputs.TAG_VERSION }} ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: ↓ Download Stage 2 Windows artifact
        uses: actions/download-artifact@v7
        with:
          name: windows-${{ env.ARCH }}-stage-2
          path: ${{ github.workspace }}
      - name: 🏗 Build
        run: |
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          else
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export USE_PGO=1
          ./mach build
      - name: 📦 Package
        run: |
          ./mach package
          if [ -d "$PWD"/waterfox/browser/locales/en-GB ]; then
            ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th uk vi zh-CN zh-TW
          fi
      - name: ↑ Upload Windows build outputs
        uses: actions/upload-artifact@v6
        with:
          name: windows-${{ env.ARCH }}-build
          path: |
            obj-${{ env.ARCH }}/dist/waterfox
            obj-${{ env.ARCH }}/dist/host/bin/mar
            obj-${{ env.ARCH }}/browser/installer/windows/instgen/
  build-macos-multi-stage-1:
    name: 🍎 macOS Stage 1
    runs-on:
      - warp-ubuntu-latest-x64-16x
    strategy:
      matrix:
        arch:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    concurrency:
      group: '${{ github.ref }}-${{ matrix.arch }}-macos-multi'
      cancel-in-progress: true
    env:
      MOZCONFIG: '.mozconfig-${{ matrix.arch }}'
    steps:
      - name: ⚡ Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 💿 Build dependencies
        run: |
          sudo apt update
          sudo apt install nasm
          rustup override set 1.90.0
          rustup target add ${{ matrix.arch }}
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L "https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
          curl https://rclone.org/install.sh | sudo bash
      - name: 📤 Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: 📣 Override version_display.txt
        run: |
          if [[ -n ${{ inputs.TAG_VERSION }} ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: 🏗 Build
        run: |
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          else
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export GEN_PGO=1
          ./mach build
      - name: 📦 Package
        run: |
          ./mach package
      - name: ↑ Upload Stage 1 Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ matrix.arch }}-stage-1
          path: |
            ./obj-${{ matrix.arch }}/dist/waterfox/*.app
            ./obj-${{ matrix.arch }}/dist/host/bin/mar
          retention-days: 1
  build-macos-multi-stage-2:
    name: 🍎 macOS Stage 2
    runs-on: ${{ matrix.runs-on }}
    concurrency:
      group: '${{ github.ref }}-${{ matrix.arch }}-macos-multi-stage-2'
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - runs-on: macos-15-intel
            arch: x86_64-apple-darwin
            clang_url: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.macosx64-clang-20.latest/artifacts/public/build/clang.tar.zst
          - runs-on: warp-macos-13-arm64-6x
            arch: aarch64-apple-darwin
            clang_url: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.macosx64-aarch64-clang-20.latest/artifacts/public/build/clang.tar.zst
    needs:
      - build-macos-multi-stage-1
    env:
      MOZ_HEADLESS: '1'
    steps:
      - name: 📤 Checkout
        uses: actions/checkout@v6
      - name: ↓ Download Stage 1 macOS artifact
        uses: actions/download-artifact@v7
        with:
          name: macos-${{ matrix.arch }}-stage-1
          path: obj-${{ matrix.arch }}/dist/
      - name: 🏗 Run PGO
        run: |
          mkdir -p $HOME/.mozbuild
          curl -L ${{ matrix.clang_url }} -o clang.tar.zst
          zstd -d clang.tar.zst
          tar -xf clang.tar
          ls obj-${{ matrix.arch }}/dist/
          ls obj-${{ matrix.arch }}/dist/waterfox
          xattr -dr com.apple.quarantine ./obj-${{ matrix.arch }}/dist/waterfox/Waterfox.app
          find ./obj-${{ matrix.arch }}/dist/waterfox/ -type f -exec /bin/sh -c "file {} | grep -q executable && chmod +x {}" \;
          rm .mozconfig || true
          ./mach --no-interactive bootstrap --application-choice=browser
          LLVM_PROFDATA=$PWD/clang/bin/llvm-profdata JARLOG_FILE=en-US.log ./mach python build/pgo/profileserver.py --binary ./obj-${{ matrix.arch }}/dist/waterfox/Waterfox.app/Contents/MacOS/waterfox
      - name: ↑ Upload Stage 2 Artifact
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ matrix.arch }}-stage-2
          path: |
            merged.profdata
            en-US.log
  build-macos-multi-stage-3:
    name: 🍎 macOS Stage 3
    runs-on:
      - warp-ubuntu-latest-x64-32x
    needs:
      - build-macos-multi-stage-2
    strategy:
      matrix:
        arch:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    concurrency:
      group: '${{ github.ref }}-${{ matrix.arch }}-macos-multi'
      cancel-in-progress: true
    env:
      MOZCONFIG: '.mozconfig-${{ matrix.arch }}'
    steps:
      - name: ⚡ Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 💿 Build dependencies
        run: |
          sudo apt update
          sudo apt install nasm
          rustup override set 1.90.0
          rustup target add ${{ matrix.arch }}
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L "https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
          curl https://rclone.org/install.sh | sudo bash
      - name: 📤 Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: 📣 Override version_display.txt
        run: |
          if [[ -n ${{ inputs.TAG_VERSION }} ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: ↓ Download Stage 2 ARM64 artifact
        uses: actions/download-artifact@v7
        with:
          name: macos-${{ matrix.arch }}-stage-2
          path: ${{ github.workspace }}
      - name: 🏗 Build
        run: |
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          else
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export USE_PGO=1
          ./mach build
      - name: 📦 Package
        run: |
          ./mach package
          if [ -d "$PWD"/waterfox/browser/locales/en-GB ]; then
            ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th uk vi zh-CN zh-TW
          fi
      - name: ↑ Upload Stage 3 Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ matrix.arch }}-stage-3
          path: |
            ./obj-${{ matrix.arch }}/dist/waterfox/*.app
            ./obj-${{ matrix.arch }}/dist/host/bin/mar
          retention-days: 1
  build-linux-x64:
    name: 🐧 Linux
    runs-on:
      - warp-ubuntu-2204-x64-16x
    concurrency:
      group: '${{ github.head_ref }}-linux-x64'
      cancel-in-progress: true
    env:
      MOZCONFIG: .mozconfig-x86_64-pc-linux-gnu
      ARCH: x86_64-pc-linux-gnu
      CARGO_INCREMENTAL: '0'
      CARGO_TERM_COLOR: always
    steps:
      - name: ⚡ Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 💿 Setup build packages
        run: |
          mkdir -p $HOME/.mozbuild
          rustup override set 1.90.0
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-20.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          curl -L "https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz" | tar xJ
          sudo mv 7zz /usr/local/bin/7z
          sudo apt install patchelf
          python3 -m pip install cryptography
      - name: 📤 Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: 📣 Override version_display.txt
        run: |
          if [[ -n ${{ inputs.TAG_VERSION }} ]]; then
            echo ${{ inputs.TAG_VERSION }} > browser/config/version_display.txt
          fi
          echo 'VERSION_DISPLAY<<EOF' >> $GITHUB_ENV
          cat browser/config/version_display.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: 🏗 Build Stage 1
        run: |
          echo "${{ secrets.MOZ_API_KEY }}" > mozilla-api
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          else
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export GEN_PGO=1
          ./mach build
      - name: 🏗 Build Stage 2
        env:
          DISPLAY: :0
        run: |
          ./mach package
          Xvfb $DISPLAY -screen 0 1280x1024x24 &
          LLVM_PROFDATA=$HOME/.mozbuild/clang/bin/llvm-profdata JARLOG_FILE=en-US.log ./mach python build/pgo/profileserver.py --binary obj-${{ env.ARCH }}/dist/waterfox/waterfox
          unset GEN_PGO
          ./mach clobber
      - name: 🏗 Build Stage 3
        run: |
          if [[ $PRE_RELEASE == 'true' ]]; then
            export WFX_PRE_RELEASE=1
            echo "Set WFX_PRE_RELEASE as ${WFX_PRE_RELEASE}"
            echo "WFX_RELEASE should be 0. ${WFX_RELEASE}"
          else
            export WFX_RELEASE=1
            echo "Set WFX_RELEASE as ${WFX_RELEASE}"
            echo "WFX_PRE_RELEASE should be 0. ${WFX_PRE_RELEASE}"
          fi
          export USE_PGO=1
          ./mach build
      - name: 📦 Package
        run: |
          ./mach package
          if [ -d "$PWD"/waterfox/browser/locales/en-GB ]; then
            ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th uk vi zh-CN zh-TW
          fi
      - name: 📦 Bundle Linux build outputs (preserve file modes)
        run: |
          DIST_ROOT="obj-${{ env.ARCH }}/dist"
          tar -C "$DIST_ROOT" -cf linux-build.tar waterfox host/bin/mar
      - name: ↑ Upload Linux build outputs
        uses: actions/upload-artifact@v6
        with:
          name: linux-build
          path: linux-build.tar
